CJRSM/CJRSM/Controllers/JeuController.cs
using CJRSM.Models.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Collections;

namespace CJRSM.Controllers
{
    public class JeuController : Controller
    {
        private IGenericRepository<Jeu> repo;
        private IUnitOfWork contexte;
        Jeu jeu;

        public JeuController()
        {
            contexte = new UnitOfWork();
            repo = contexte.Jeu;
        }

        public JeuController(IUnitOfWork contexte)
        {
            this.contexte = contexte;
            repo = contexte.Jeu;
        }

        // Retourne la vue Index, si les paramètres passés ne sont pas nul,
        //      un trie sera effectué et la liste des jeux restant sera retourné
        public ActionResult Index(string ChercherTitre,
                                    int id = 0,
                                    int Difficulte = 0,
                                    int NbrJoueurMin = 0,
                                    int NbrJoueurMax = 0,
                                    int TempsMin = 0,
                                    int TempsMax = 0,
                                    int TypesId = 0)
        {
            // Création du dictionnaire
            Dictionary<int, Jeu> dictionnaireJeu = new Dictionary<int, Jeu>();
            IEnumerable<Jeu> iEnumJeu = repo.Get(j => j.Titre.Contains(""));
            IEnumerable<TypesJeu> iEnumTypesJeu = contexte.TypesJeu.Get(tj => tj.Id.ToString().Contains(""));
            List<Jeu> listeJeu = new List<Jeu>();
            List<TypesJeu> listeTypesJeu = new List<TypesJeu>();
            listeJeu = iEnumJeu.ToList();
            listeTypesJeu = iEnumTypesJeu.ToList();

            // Attribution de toutes les valeurs ainsi que des clefs au dicitonnaire
            for (int i = 0; i < iEnumJeu.Count(); i++)
            {
                dictionnaireJeu.Add(i, listeJeu[i]);
            }

            // Trie du dictionnaire selon l'utilisateur
            if (ChercherTitre != "" && ChercherTitre != null)
            {
                for (int i = 0; i <= dictionnaireJeu.Count(); i++)
                {
                    if (!dictionnaireJeu[i].Titre.Contains(ChercherTitre))
                    {
                        dictionnaireJeu.Remove(i);
                    }
                }
            }
            listeJeu = dictionnaireJeu.Values.ToList();
            dictionnaireJeu = new Dictionary<int, Jeu>();
            for (int i = 0; i < listeJeu.Count(); i++)
            {
                dictionnaireJeu.Add(i, listeJeu[i]);
            }
            if (id != 0)
            {
                dictionnaireJeu = new Dictionary<int, Jeu>();
                jeu = contexte.Jeu.Find(id);
                dictionnaireJeu.Add(1, jeu);
            }
            listeJeu = dictionnaireJeu.Values.ToList();
            dictionnaireJeu = new Dictionary<int, Jeu>();
            for (int i = 0; i < listeJeu.Count(); i++)
            {
                dictionnaireJeu.Add(i, listeJeu[i]);
            }
            if (Difficulte != 0)
            {
                for (int i = 0; i <= dictionnaireJeu.Count(); i++)
                {
                    if (dictionnaireJeu[i].Difficulte != Difficulte)
                    {
                        dictionnaireJeu.Remove(i);
                    }
                }
            }
            listeJeu = dictionnaireJeu.Values.ToList();
            dictionnaireJeu = new Dictionary<int, Jeu>();
            for (int i = 0; i < listeJeu.Count(); i++)
            {
                dictionnaireJeu.Add(i, listeJeu[i]);
            }
            if (NbrJoueurMin != 0)
            {
                for (int i = 0; i <= dictionnaireJeu.Count(); i++)
                {
                    if (dictionnaireJeu[i].NbrJoueurMin < NbrJoueurMin)
                    {
                        dictionnaireJeu.Remove(i);
                    }
                }
            }
            listeJeu = dictionnaireJeu.Values.ToList();
            dictionnaireJeu = new Dictionary<int, Jeu>();
            for (int i = 0; i < listeJeu.Count(); i++)
            {
                dictionnaireJeu.Add(i, listeJeu[i]);
            }
            if (NbrJoueurMax != 0)
            {
                for (int i = 0; i < dictionnaireJeu.Count(); i++)
                {
                    if (dictionnaireJeu[i].NbrJoueurMax > NbrJoueurMax)
                    {
                        dictionnaireJeu.Remove(i);
                    }
                }
            }
            listeJeu = dictionnaireJeu.Values.ToList();
            dictionnaireJeu = new Dictionary<int, Jeu>();
            for (int i = 0; i < listeJeu.Count(); i++)
            {
                dictionnaireJeu.Add(i, listeJeu[i]);
            }
            if (TempsMin != 0)
            {
                for (int i = 0; i <= dictionnaireJeu.Count(); i++)
                {
                    if (dictionnaireJeu[i].TempsMin < TempsMin)
                    {
                        dictionnaireJeu.Remove(i);
                    }
                }
            }
            listeJeu = dictionnaireJeu.Values.ToList();
            dictionnaireJeu = new Dictionary<int, Jeu>();
            for (int i = 0; i < listeJeu.Count(); i++)
            {
                dictionnaireJeu.Add(i, listeJeu[i]);
            }
            if (TempsMax != 0)
            {
                for (int i = 0; i <= dictionnaireJeu.Count(); i++)
                {
                    if (dictionnaireJeu[i].TempsMax > TempsMax)
                    {
                        dictionnaireJeu.Remove(i);
                    }
                }
            }
            listeJeu = dictionnaireJeu.Values.ToList();
            dictionnaireJeu = new Dictionary<int, Jeu>();
            for (int i = 0; i < listeJeu.Count(); i++)
            {
                dictionnaireJeu.Add(i, listeJeu[i]);
            }
            if (TypesId != 0)
            {
                listeJeu = new List<Jeu>();
                for (int i = 0; i <= listeTypesJeu.Count(); i++)
                {
                    if (TypesId == listeTypesJeu[i].IdTypes)
                    {
                        for (int j = 0; j < dictionnaireJeu.Count(); j++)
                        {
                            if (listeTypesJeu[i].IdJeu == dictionnaireJeu[j].Id)
                            {
                                listeJeu.Add(dictionnaireJeu[j]);
                            }
                        }
                    }
                }
            }
            dictionnaireJeu = new Dictionary<int, Jeu>();
            for (int i = 0; i < listeJeu.Count(); i++)
            {
                dictionnaireJeu.Add(i, listeJeu[i]);
            }

            // Retour du dictionnaire a un IEnumerable pour le retour a la page HTML
            iEnumJeu = dictionnaireJeu.Values;
            return View(iEnumJeu);
        }

        // Retourne la vue modifier avec le jeu selectionné par l'utilisateur selon son ID
        public ActionResult Modifier(int id)
        {
            jeu = contexte.Jeu.Find(id);
            return View(jeu);
        }

        // Retourne la vue modifier avec le jeu nouvellement modifié par l'utilisateur
        [HttpPost]
        public ActionResult Modifier(Jeu jeuModifier)
        {
            if (ModelState.IsValid)
            {
                jeu = new Jeu();
                jeu.Modifier(jeu, contexte);
                return RedirectToAction("Index", "Jeu");
            }
            else
                return View(jeu);
        }

        // Retourne la vue supprimer avec le jeu selectionné par l'utilisateur selon son ID
        public ActionResult Supprimer(int id)
        {
            jeu = contexte.Jeu.Find(id);
            return View(jeu);
        }

        // Retourne l'utilisateur a la liste de jeu avec ce dernier nouvellement supprimé par l'utilisateur
        [HttpPost]
        public ActionResult Supprimer(Jeu jeuSupprimer)
        {
            if (ModelState.IsValid)
            {
                jeuSupprimer.Supprimer(jeuSupprimer, contexte);

                return RedirectToAction("Index", "Jeu");
            }
            else
                return View(jeuSupprimer);
        }
    }
}

CJRSM/CJRSM/Controllers/TypesJeuController.cs
using System.Web.Mvc;
using CJRSM.Models.DAL;

namespace CJRSM.Controllers
{
    public class TypesJeuController : Controller
    {
        private IGenericRepository<TypesJeu> repo;
        private IUnitOfWork contexte;
        TypesJeu typesJeu;

        public TypesJeuController()
        {
            contexte = new UnitOfWork();
            repo = contexte.TypesJeu;
        }

        public TypesJeuController(IUnitOfWork contexte)
        {
            this.contexte = contexte;
            repo = contexte.TypesJeu;
        }

        // Retourne la vue Ajout
        public ActionResult Ajout()
        {
            return View();
        }

        // Retourne la vue details après avoir créer le nouveau lien de
        //      TypesJeu entre le jeu et le type sélectionné
        [HttpPost]
        public ActionResult Ajout(TypesJeu nouveaulien)
        {
            if (ModelState.IsValid)
            {
                typesJeu = new TypesJeu();
                return View("Details", typesJeu.AjouterLienTypes(nouveaulien, contexte));
            }else
                return View(typesJeu);
        }
    }
}

CJRSM/CJRSM/Views/Jeu/Index.cshtml
@model IEnumerable<CJRSM.Models.DAL.Jeu>

@{
    ViewBag.Title = "Index";
    var listeDifficulte = new List<SelectListItem>{
        new SelectListItem { Text = "0", Value = "0" },
        new SelectListItem { Text = "1", Value = "1" },
        new SelectListItem { Text = "2", Value = "2" },
        new SelectListItem { Text = "3", Value = "3" },
        new SelectListItem { Text = "4", Value = "4" },
        new SelectListItem { Text = "5", Value = "5" }
    };
    CJRSM.Models.DAL.IMembre membre = new CJRSM.Models.DAL.Membre();
    CJRSM.Models.DAL.IUnitOfWork contexte = new CJRSM.Models.DAL.UnitOfWork();
    membre = membre.Trouver(User.Identity.Name, contexte);
}

<div class="conteneur_Unique">
    <input type="checkbox" class="etat_Derouler" id="post-2" />
    <label for="post-2" class="option_derouler"></label>
    <div class="cible_Deroulante">
        @using (Html.BeginForm())
        {
            <table class="table_Recherche">
                <tr>
                    <th style="padding-top:20px;">
                        <h2>Rechercher un jeu</h2>
                    </th>
                </tr>
                <tr>
                    <th>Trouver un jeu par son numéro d'identification :</th>
                    <th>@Html.TextBox("id", "")</th>
                </tr>
                <tr>
                    <th>Trouver un jeu par son titre :</th>
                    <th>@Html.TextBox("ChercherTitre", "", new { onKeyup ="showResult(this.value)"})</th>
                </tr>
                <tr>
                    <th>Trouver un jeu par sa difficulté</th>
                    <th>@Html.DropDownList("Difficulte", listeDifficulte)</th>
                </tr>
                <tr>
                    <th>Trouver un jeu par son nombre minimal de joueur</th>
                    <th>@Html.TextBox("NbrJoueurMin", "")</th>
                </tr>
                <tr>
                    <th>Trouver un jeu par son nombre maximal de joueur</th>
                    <th>@Html.TextBox("NbrJoueurMax", "")</th>
                </tr>
                <tr>
                    <th>Trouver un jeu par sa durée minimal</th>
                    <th>@Html.TextBox("TempsMin", "")</th>
                </tr>
                <tr>
                    <th>Trouver un jeu par sa durée maximal</th>
                    <th>@Html.TextBox("TempsMax", "")</th>
                </tr>
                <tr>
                    <th>Trouver un jeu par ses types</th>
                    <th>
                        <input name="TypesId" list="types" id="TypesId"/>
                        <datalist id="types">
                            @foreach (var i in contexte.Types.Get())
                            {
                                <option value="@i.Id">@i.Nom</option>
                            }
                        </datalist>
                    </th>
                </tr>
                <tr>
                    <th></th>
                    <th></th>
                    <th>
                        <input type="reset" value="Vider les champs de recherche" />
                    </th>
                </tr>
                <tr>
                    <th></th>
                    <th></th>
                    <th>
                        <input type="submit" value="Trouver un Jeu" />
                    </th>
                </tr>
            </table>
        }
    </div>

    <h2>Listes des Jeux</h2>
    @if (User.Identity.Name != "")
    {
        <h3>@Html.ActionLink("Ajouter un type", "Ajout", "TypesJeu")</h3>
    }
    <div class="table_transition">
        <table class="table_Liste sortable">
            <tr>
                <th>Titre</th>
                <th>Difficulté</th>
                <th>Minimum de joueur</th>
                <th>Maximum de joueur</th>
                <th>Temps Minimal</th>
                <th>Temps Maximal</th>
                <th>Date d'ajout</th>
                <th>Types de Jeu</th>
                <th>Disponible</th>
                @if (membre.Role != "Membre" && User.Identity.Name != "")
                {
                    <th></th>
                }
            </tr>

            @if (Model != null)
            {
                foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Titre)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Difficulte)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NbrJoueurMin)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NbrJoueurMax)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TempsMin) minute-s
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TempsMax) minute-s
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DateAjout.Day)/@Html.DisplayFor(modelItem => item.DateAjout.Month)/@Html.DisplayFor(modelItem => item.DateAjout.Year)
                        </td>
                        <td>
                            <div class="div_type">
                                @{
                                    IEnumerable<CJRSM.Models.DAL.TypesJeu> TypesJeu = contexte.TypesJeu.Get();
                                    IEnumerable<CJRSM.Models.DAL.Type> Type = contexte.Types.Get();
                                    foreach (var tj in TypesJeu){
                                        if (tj.IdJeu == item.Id){
                                            foreach (var t in Type){
                                                if (tj.IdTypes == t.Id){
                                                    <div class="type_tag">
                                                        @Html.DisplayFor(modelItem => t.Nom)
                                                    </div>
                                                }
                                            }
                                        }
                                    }
                                }
                            </div>
                        </td>
                        <td class="div_disponible">
                            @if (item.LocationJeu != null)
                            {
                                <img src="~/Content/icon_false.png" style="height:20px;" />}
                            else
                            {
                                <img src="~/Content/icon_true.png" style="height:20px;" />}
                        </td>
                        @if (membre.Role != "Membre" && User.Identity.Name != "")
                        {
                            <td>
                                @Html.ActionLink("Modifier", "Modifier", new { id = item.Id })
                                @Html.ActionLink("Supprimer", "Supprimer", new { id = item.Id })
                            </td>
                        }
                    </tr>
                }
            }
        </table>
    </div>
</div>

CJRSM/CJRSM/Views/Jeu/Modifier.cshtml
@model CJRSM.Models.DAL.Jeu

@{
    ViewBag.Title = "Modifier un jeu";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="conteneur_Unique">
        <h2>Modifier un jeu</h2>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            <label class="control-label col-md-2">Titre</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Difficulté</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Difficulte, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Difficulte, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Nombre de joueur minimal</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.NbrJoueurMin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NbrJoueurMin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Nombre de joueur maximal</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.NbrJoueurMax, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NbrJoueurMax, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Temps minimal</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.TempsMin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TempsMin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Temps maximal</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.TempsMax, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TempsMax, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Sauvegarder les modifications" class="btn btn-default" />
            </div>
        </div>
        @Html.ActionLink("Retourner a la liste des jeux", "Index")
    </div>
}

CJRSM/CJRSM/Views/Jeu/Supprimer.cshtml
@model CJRSM.Models.DAL.Jeu

@{
    ViewBag.Title = "Supprimer";
}

<div class="conteneur_Unique">
    <h2>Supprimer un jeu</h2>
    <h3>Voulez-vous vraiment supprimer ce jeu?</h3>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Titre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Difficulte)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Difficulte)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NbrJoueurMin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NbrJoueurMin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NbrJoueurMax)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NbrJoueurMax)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TempsMin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TempsMin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TempsMax)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TempsMax)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateAjout)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateAjout)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdLocationJeu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdLocationJeu)
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Supprimer le jeu" class="btn btn-default" /> |
            @Html.ActionLink("Retourner a la liste des jeux", "Index")
        </div>
    }
</div>